---
project_name: glonner

builds:
    - env:
          - CGO_ENABLED=0
      goos:
          - linux
          - windows
          - darwin
      goarch:
          - amd64
          - arm
          - arm64

release:
    prerelease: auto


brews:
    - tap:
          owner: Excoriate
          name: homebrew-tap
          branch: main

      url_template: https://github.com/Excoriate/glonner-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}

      commit_author:
          name: Excoriate
          email: alex@ideaup.cl

      folder: Formula
      homepage: https://github.com/Excoriate/glonner-cli
      description: A CLI tool for devour repositories within a given GitHub organization.
      license: Apache-2.0

archives:
    - wrap_in_directory: true

      format_overrides:
          - goos: windows
            format: zip
checksum:
    name_template: checksums.txt

snapshot:
    name_template: '{{ .Tag }}-next'

changelog:
    sort: asc
    filters:
        exclude:
            - '^docs:'
            - '^test:'
            - '^*.md:'
