---
run:
    tests: false
    timeout: 240s
linters-settings:
    govet:
        check-shadowing: false
    golint:
        min-confidence: 0
    gocyclo:
        min-complexity: 15
    maligned:
        suggest-new: true
    dupl:
        threshold: 100
    goconst:
        min-len: 5
        min-occurrences: 3
    depguard:
        list-type: blacklist
        packages:
    gocritic:
        settings:
            rangeValCopy:
                sizeThreshold: 1024
        enabled-tags:
            - diagnostic
            - experimental
            - opinionated
            - performance
            - style
        disabled-checks:
            - singleCaseSwitch #nice for expandability,
            - hugeParam #maybe disable for high performance lambdas
            - appendCombine #multiple appends can be nice visually
    funlen:
        lines: 100
        statements: 52

linters:
    disable-all: true
    enable:
        - bodyclose
        - deadcode
        - depguard
        - dogsled
        - dupl
        - errcheck
        - funlen
        - goconst
        - gocritic
        - gofmt
        - gosec
        - gosimple
#        - ineffassign
        - nakedret
        - exportloopref
        - staticcheck
        - structcheck
        - stylecheck
        - typecheck
        - unconvert
        - unparam
        - unused
        - varcheck
        - whitespace
        - govet

issues:
    max-issues-per-linter: 0
    max-same-issues: 0
    exclude-rules:
        - linters:
              - gosec
          text: G306
        - linters:
              - gosec
          text: G404

output:
    format: line-number
