---
name: 'CI: Container'

on: [push, pull_request]

defaults:
    run:
        shell: bash
        working-directory: app

jobs:
    ci:
        name: Lint Docker image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Lint Dockerfile
              id: lint-dockerfile
              uses: hadolint/hadolint-action@master
              with:
                  dockerfile: app/Dockerfile
                  ignore: DL3006
                  verbose: true

    build:
        name: Build Container Image
        runs-on: ubuntu-latest
        needs: [ci]

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Build
              id: build-and-run
              run: |
                  docker build -t glonner:latest .
