---
name: Generate Version Manual

on:
    workflow_dispatch:
    push:
        branches:
            - main

defaults:
    run:
        shell: bash

jobs:

    generate-version:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: '0'

            - name: Generate tag & bump version
              uses: anothrNick/github-tag-action@1.36.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
