---
name: Generate Version Automatically

on:
    push:
        branches:
            - main
            - master

defaults:
    run:
        shell: bash

jobs:

    generate-version:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: '0'

            - uses: actions-ecosystem/action-get-merged-pull-request@v1
              id: get-merged-pull-request
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}

            - uses: actions-ecosystem/action-release-label@v1
              id: release-label
              if: ${{ steps.get-merged-pull-request.outputs.title != null }}
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  labels: ${{ steps.get-merged-pull-request.outputs.labels }}

            - uses: actions-ecosystem/action-get-latest-tag@v1
              id: get-latest-tag
              if: ${{ steps.release-label.outputs.level != null }}
              with:
                  semver_only: true

            - uses: actions-ecosystem/action-bump-semver@v1
              id: bump-semver
              if: ${{ steps.release-label.outputs.level != null }}
              with:
                  current_version: ${{ steps.get-latest-tag.outputs.tag }}
                  level: ${{ steps.release-label.outputs.level }}

            - uses: actions-ecosystem/action-regex-match@v2
              id: regex-match
              if: ${{ steps.bump-semver.outputs.new_version != null }}
              with:
                  text: ${{ steps.get-merged-pull-request.outputs.body }}
                  regex: '```release_note([\s\S]*)```'

            - uses: actions-ecosystem/action-push-tag@v1
              if: ${{ steps.bump-semver.outputs.new_version != null }}
              with:
                  tag: ${{ steps.bump-semver.outputs.new_version }}
                  message: '${{ steps.bump-semver.outputs.new_version }}: PR #${{ steps.get-merged-pull-request.outputs.number }} ${{ steps.get-merged-pull-request.outputs.title
                      }}'
